version: "3"
services:
  server:
    depends_on:
      - redis
      - rabbitmq
      - otel-collector
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - RESULT_BACKEND=redis://redis:6379/0
      - OTEL_SERVICE_NAME=foo_server
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    ports:
      - "8000:8000"
    command: opentelemetry-instrument uvicorn main:app --log-level info --proxy-headers --host 0.0.0.0 --port 8000
    # command: uvicorn main:app --host 0.0.0.0 --port 8000

  worker:
    deploy:
      replicas: 2
    depends_on:
      - redis
      - rabbitmq
      - otel-collector
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
      - OTEL_SERVICE_NAME=foo_worker
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_LOG_LEVEL="debug"
    command: celery -A task worker --loglevel=info --task-events --concurrency=1

  redis:
    image: redis
    ports:
    - "6379:6379"

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    image: rabbitmq
    ports:
      - "5672:5672"

  otel-collector:
    depends_on:
      - jaeger
    image: otel/opentelemetry-collector:0.45.0
    command:
      - --config=/etc/otel/collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
    volumes:
      - ${PWD}/local-otel-collector-config.yaml:/etc/otel/collector-config.yaml
    environment:
      OTEL_LOG_LEVEL: "debug"

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
